### ISSUE TITLE
could not find the  url: https://github.com/prooph/php-ddd-cargo-sample

### ISSUE THREAD

**Issue by joostshao** [codeliner/php-ddd-cargo-sample#24]
could not find the  url: https://github.com/prooph/php-ddd-cargo-sample

**Comment by joostshao** [comment]
in  these files:
https://github.com/codeliner/php-ddd-cargo-sample/blob/2612f3d2a756b224236d6d0c0a079305780c02d3/composer.json

https://github.com/codeliner/php-ddd-cargo-sample/blob/f153ed52a04dbd32c6f41a5611776a8a27a1f96e/CargoUI/view/riot/home.html

https://github.com/codeliner/php-ddd-cargo-sample/blob/1ef44efe3969daac992d030d016577b1c84458c5/docs/installation.md

**Comment by codeliner** [comment]
good catch! I've updated the files
