### ISSUE TITLE
HTTP is User Interface

### ISSUE THREAD

**Issue by danizord** [codeliner/php-ddd-cargo-sample#26]
I'm wondering if these action middlewares should not be moved to user interface namespace.

I think application layer should not depend on UI details, so that we can introduce a new UI (CLI, for example), without changing the application layer.

**Comment by codeliner** [comment]
Maybe the action middlewares should be moved to their own namespace inside the CargoBackend. I would not move them to the UI as the CargoBackend is a self-contained context. Imagine it runs in a Microservices architecture without the UI. The CargoBackend need to provide a HTTP API in front of the application layer (BookingService in the cargo sample).
What about moving the action middlewares to `Codeliner\CargoBackend\Http\Action` ?
Then it would be possible to also have `Codeliner\CargoBackend\Cli\Command` or similar.

**Comment by danizord** [comment]
>What about moving the action middlewares to Codeliner\CargoBackend\Http\Action ?

@codeliner looks good!

**Comment by codeliner** [comment]
great! A PR would be nice ;)
