### ISSUE TITLE
Container factories are part of infrastructure?

### ISSUE THREAD

**Issue by danizord** [codeliner/php-ddd-cargo-sample#27]
Looking at http://dddsample.sourceforge.net/architecture.html
>In addition to the three vertical layers, there is also the infrastructure. As the the picture shows, it supports all of the three layers in different ways, facilitating communication between the layers

>Also, we consider code and configuration files that glues the other layers to the infrastructure as part of the infrastructure layer.

Seems like container factories fits the infraestructure layer as it's glue code between our classes and the infraestructure stuff. So, I think we could move `Container` namespace under `Infrasestructure`.

What do you think?

**Comment by codeliner** [comment]
@danizord +1 This would clean up the [src](https://github.com/codeliner/php-ddd-cargo-sample/tree/master/CargoBackend/src)

Can you provide a PR?
