### ISSUE TITLE
Upgrade to expressive 2.0 and PSR-15 middlewares

### ISSUE THREAD

**Issue by codeliner** [codeliner/php-ddd-cargo-sample#33]
Would be nice to reflect latest changes in the PHP middleware area.

Migrate to expressive 2.0: 
- https://framework.zend.com/blog/2017-03-07-expressive-2.html
- https://docs.zendframework.com/zend-expressive/reference/migration/to-v2/

Migrate middlewares to support PSR-15:
- https://github.com/php-fig/fig-standards/tree/master/proposed/http-middleware
- https://docs.zendframework.com/zend-expressive/reference/migration/to-v2/#http-interop

**Comment by codeliner** [comment]
If **YOU** want to work on the issue please drop me a note here!

**Comment by danizord** [comment]
@codeliner I can handle this one next weekend :)

**Comment by codeliner** [comment]
cool, thx @danizord

**Comment by codeliner** [comment]
@danizord any updates?
@snapshotpl Might want to take this one, too? ;)

**Comment by snapshotpl** [comment]
@codeliner :+1:

**Comment by codeliner** [comment]
Closed by #44
