### ISSUE TITLE
Bump PHP version to 7.1

### ISSUE THREAD

**Issue by codeliner** [codeliner/php-ddd-cargo-sample#34]
and make use of PHP 7.1 where possible like `void` return type here:
https://github.com/codeliner/php-ddd-cargo-sample/blob/master/CargoBackend/src/Application/Booking/BookingService.php#L157

**Comment by codeliner** [comment]
If **YOU** want to work on the issue please drop me a note here.

**Comment by snapshotpl** [comment]
I take it!

**Comment by codeliner** [comment]
Closed by #40
