### ISSUE TITLE
DDD with Symfony 4

### ISSUE THREAD

**Issue by Kwadz** [codeliner/php-ddd-cargo-sample#53]
Since Symfony is widely used by the PHP community, is it possible to provide a project using Symfony 4 with a [folder-by-feature](https://dzone.com/articles/package-by-layer-for-spring-projects-is-obsolete) structure?

**Comment by prolic** [comment]
Sure, send some money. Otherwise you probably would have to do it yourself.
Sorry if this sounds harsh, but this is an open source project and we have
only limited resources.

**Comment by Kwadz** [comment]
No worries, I supposed some maintainers use Symfony, since it's rare nowadays using PHP without any framework.

**Comment by prolic** [comment]
prooph maintainers are rare :)

Sascha-Oliver Prolic


Am Di., 11. Dez. 2018 um 18:03 Uhr schrieb Kwadz <notifications@github.com>:

**Comment by codeliner** [comment]
Oh some money would be nice. Good idea @prolic ;)

DDDesign itself is not about frameworks. Anyway, choosing a good framework to handle http requests, authentication, authorization, etc. is important for every project and can be part of tactical DDDesign, but it highly depends on existing team Skills. It's not the focus of this example project.
Feel free to fork the example and replace zend-expressive with Symfony. Send me a link to your fork and I'd be happy to add it to the readme.

**Comment by Kwadz** [comment]
I was more focus on the architecture than the framework components. Anyway, thanks for your answers. If I have the time to create an example using Symfony 4, I'll send you the link ;)
